---
rules:
  line-length:
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false

ignore: |
  .git/
  venv/
  .circleci/
