[build]
command = """
    set -e
    export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp.json"
    echo "$GCLOUD_SERVICE_KEY" > "$GOOGLE_APPLICATION_CREDENTIALS"
    ./bin/generator namespaces
    mkdir site
    cp namespaces.yaml site
    echo '<html><body>See <a href=\"/namespaces.yaml\">namespaces.yaml</a>.</body></html>' > site/index.html
"""
environment = { PYTHON_VERSION = "3.8" }
publish = "site"
