[build]
command = """
    set -e
    ./bin/generator namespaces
    mkdir site
    cp namespaces.yaml site
    echo '<html><body>See <a href=\"/namespaces.yaml\">namespaces.yaml</a>.</body></html>' > site/index.html
"""
environment = { PYTHON_VERSION = "3.8" }
publish = "site"
