name: Deploy API docs to gh-pages
on:
  push:
    branches:
      - main
      - docs
jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          pip install -r requirements.txt
          pdoc -o _docs generator
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _docs
